/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panel;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
//import java.text.ParseException;
//import java.text.SimpleDateFormat;
//import java.util.Comparator;
//import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
//import javax.swing.ListSelectionModel;
//import javax.swing.event.TableModelEvent;
import javax.swing.table.DefaultTableModel;
//import javax.swing.table.TableModel;
//import javax.swing.table.TableRowSorter;

/**
 *
 * @author Nikx
 */
public class pnl_gk extends javax.swing.JPanel {
    
private Connection conn = new koneksi().connect();
    DefaultTableModel tbll;
    DefaultTableModel tabmode;
//    private Random generator;
//    private TableRowSorter<DefaultTableModel>sorter;            
            
    /**
     * Creates new form pnl_home
     */
    
    public pnl_gk() {
        initComponents();
        datatable();
//        datatable();
    }

//    public boolean isCellEditable(int row, int col)
//        { return true; }
//    public void setValueAt(Object value, int row, int col) {
//        tabel_gk[row][col] = value;
//        fireTableCellUpdated(row, col);
//    }
    
//    public void tableChanged(TableModelEvent e) {
//        int row = e.getFirstRow();
//        int column = e.getColumn();
//        TableModel model = (TableModel)e.getSource();
//        Object data = model.getValueAt(row, column);
//    }
    
    private void datatable(){
        Object[] Baris ={"Nomor Pegawai","Nama Karyawan","Gaji Pokok","Tunjangan","Upah Lembur","Potongan","Total Gaji"};
        tabmode = new DefaultTableModel(null, Baris);
        tabel_gk.setModel(tabmode);
        String sql = "select * from gaji inner join dk on gaji.nip = dk.nip inner join jabatan on gaji.kd_jabatan = jabatan.kd_jabatan inner join golongan on gaji.gol = golongan.gol inner join lembur on gaji.id_lembur = lembur.id_lembur";
        try {
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){
                String a = hasil.getString("nip");
                String b = hasil.getString("nama");
                String c = hasil.getString("gaji_pokok");
                String d = hasil.getString("tunjangan_jabatan");
                String e = hasil.getString("upah_lembur");
                String f = hasil.getString("total_potongan");
                String g = hasil.getString("total_gaji");
                
            
                String[] data={a,b,c,d,e,f,g};
                tabmode.addRow(data);
            }
        } catch (Exception e){}
    }
    
//    private void sort1(){
//    try {
//        generator = new Random();
//        DefaultTableModel tbl1 = new DefaultTableModel(); 
//        Connection kon =new koneksi().connect(); 
//        Statement stt1 =  kon.createStatement();
//          tbl1.addColumn("nip");
//          tbl1.addColumn("nama");
//          tbl1.addColumn("gaji_pokok");
//          tbl1.addColumn("tunjangan_jabatan");
//          tbl1.addColumn("upah_lembur");
//          tbl1.addColumn("total_potongan");
//          tbl1.addColumn("total_gaji");
//          String sql1 = "select dk.nip,dk.nama,jabatan.gaji_pokok,golongan.tunjangan_jabatan,lembur.upah_lembur,gaji.total_potongan,gaji.total_gaji from gaji inner join dk on gaji.nip = dk.nip inner join jabatan on gaji.kd_jabatan = jabatan.kd_jabatan inner join golongan on gaji.gol = golongan.gol inner join lembur on gaji.id_lembur = lembur.id_lembur ";
//          
//            ResultSet rs1= stt1.executeQuery(sql1);
//            while(rs1.next()){
//            tbl1.addRow(new Object[]{rs1.getString(1),rs1.getString(2),
//            rs1.getString(3),rs1.getString(4),rs1.getString(5),rs1.getString(6),rs1.getString(7)});}            
//          sorter = new TableRowSorter<>(tbl1);
//          sorter.setComparator(1, new Comparator<Integer>() {
//              @Override
//              public int compare(Integer o1, Integer o2) {
//                  return o1.compareTo(o2);
//              }
//          });
//          tabel_gk.setModel(tbl1);
//          tabel_gk.setRowSorter(sorter);
//    } catch (SQLException ex) {
//        Logger.getLogger(pnl_gk.class.getName()).log(Level.SEVERE, null, ex);
//    }
//    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_gk = new javax.swing.JTable();
        nip = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1010, 533));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("GAJI KARYAWAN");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, -1, -1));

        tabel_gk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_gk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_gkMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_gk);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 757, 326));

        nip.setPreferredSize(new java.awt.Dimension(0, 0));
        add(nip, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, -1, -1));

        jButton1.setText("Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonRiple1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRiple1ActionPerformed
        tambah_gk tgk = new tambah_gk();
       tgk.setVisible(true);
    }//GEN-LAST:event_rSButtonRiple1ActionPerformed

    private void tabel_gkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_gkMouseClicked
       int bar = tabel_gk.getSelectedRow();
       String a = tbll.getValueAt(bar, 0).toString();
       
       nip.setText(a);
    }//GEN-LAST:event_tabel_gkMouseClicked

    private void rSButtonRiple3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRiple3ActionPerformed
//        tabel_gk.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
//       int[] selectedRows = tabel_gk.getSelectedRows(); 
        int ok = JOptionPane.showConfirmDialog(null, "Yakin untuk di hapus ?","Konfirmasi Dialog", JOptionPane.YES_NO_OPTION);
         if (ok==0){
//           String sql="DELETE FROM gaji WHERE nip in (";
//          for( int i=0; i<selectedRows.length ; i++){
//              int row = selectedRows[i]; 
//      String name = tabmode.getValueAt(row, 0).toString();
//    sql += "\'"+name+"\'";
//    if (i<selectedRows.length-1)
//        sql+=",";
//}
//sql+=")";          
           String sql = "delete from gaji where nip ='"+nip.getText()+"'";
           try {
               
               PreparedStatement stat = conn.prepareStatement(sql);
               stat.executeUpdate();
               JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
               datatable();
//               datatable();
           }catch (SQLException e){
               JOptionPane.showMessageDialog(null, "Data gagal dihapus"+e);
           }
       }
    }//GEN-LAST:event_rSButtonRiple3ActionPerformed

    private void rSButtonRiple2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRiple2ActionPerformed
        ubah_gk ugk = new ubah_gk();
       ugk.setVisible(true);
       int bar = tabel_gk.getSelectedRow();
       String a = tbll.getValueAt(bar, 0).toString();
       String f = tbll.getValueAt(bar, 5).toString();
       String g = tbll.getValueAt(bar, 6).toString();

       ugk.nip.setSelectedItem(a);
       
//       try{
//          String sql="select * from potongan where";
//          PreparedStatement pst = conn.prepareStatement(sql);
//          ResultSet rs=pst.executeQuery(sql);
//          
//          while(rs.next()){
//          String a =rs.getString("nama_potongan");
//          String b =rs.getString("jumlah_potongan");
//          m.addElement(a);
//          }
//        }catch(Exception e){
//        JOptionPane.showMessageDialog(null,e);
//        }
       
       ugk.total_gaji.setText(g);
        
    }//GEN-LAST:event_rSButtonRiple2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        datatable();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nip;
    public static javax.swing.JTable tabel_gk;
    // End of variables declaration//GEN-END:variables
}
